[build]
  command = "cd 'one part/my-protofile-main/project' && npm install && npm run build"
  publish = "one part/my-protofile-main/project/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"